INJIMOB-978 - Update workflow to support js and kotlin publish
mosip/inji-vci-client pull request #13
Opened 2024-07-08 06:18 UTC by adityankannan-tw

2024-07-09 10:16 UTC, KiruthikaJeyashankar approved these changes

2024-07-09 10:16 UTC, KiruthikaJeyashankar commented on .github/workflows/publish-maven-npm.yml
> +        default: 'Triggered for inji-vc-client Updates'
inji-vci-client instead of inji-vc-client

2024-07-09 10:17 UTC, KiruthikaJeyashankar requested changes
inji-vci-client instead of inji-vc-client

2024-07-12 04:42 UTC, KiruthikaJeyashankar approved these changes

2024-07-12 04:43 UTC, adityankannan-tw commented
> inji-vci-client instead of inji-vc-client

done

2024-07-12 04:44 UTC, KiruthikaJeyashankar approved these changes

2024-07-15 05:28 UTC, swatigoel requested changes

2024-07-15 05:28 UTC, swatigoel commented on .github/workflows/publish-maven-npm.yml
> +      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
secret should be SLACK_WEBHOOK_INJI_TEAM

2024-07-15 18:10 UTC, swatigoel approved these changes

2024-07-15 18:10 UTC, merged